### ISSUE TITLE
error while installing gtkdialog

### ISSUE THREAD

**Issue by yalin** [bm16ton/syn-gui#1]
When I run the sh file ./install-gtkdialog.sh, at the end it gives this error.

`dpkg-buildpackage: error: failed to sign .buildinfo file
dpkg: error: cannot access archive '../gtkdialog_0.8.3-3mx17+16_arm64.deb': No such file or directory
`

**Comment by bm16ton** [comment]
crap my bad probly changed the filename and didnt update script. after the
failure try running sudo dpkg -i ../gtkdialog*.deb

**Comment by yalin** [comment]
yes, I already able to install but I just wanted to inform :) so you can make it generic.
Thank you

**Comment by bm16ton** [comment]
you da man! ill fix it as soon as i get in front of pc..it still amazes me
people stumble upon my github..i love gtkdialog so simple but can make
awesome guis
